export type Product = {
  readonly name: string;
  readonly price: string;
  readonly category: string;
  readonly asin: string;
  readonly featured: boolean;
  readonly image?: string;
};

export const AFFILIATE_TAG = "hotelshop-20";

// Google Drive image helper
const driveImg = (id: string): string =>
  `https://drive.google.com/uc?export=view&id=${id}`;

export function getProductImage(product: Product): string {
  if (product.image) return product.image;
  return '';
}

export function getProductUrl(asin: string): string {
  if (asin.startsWith('http')) return asin;
  return `https://www.amazon.com/dp/${asin}?tag=${AFFILIATE_TAG}`;
}

export function getProductsByCategory(category: string): readonly Product[] {
  return products.filter(p => p.category === category);
}

export function getFeaturedProducts(): readonly Product[] {
  return products.filter(p => p.featured);
}

export const CATEGORIES = [
  { slug: "bathroom", label: "Hotel Bathroom" },
  { slug: "kitchen", label: "Hotel Kitchen" },
  { slug: "bedroom", label: "Hotel Bedroom" },
  { slug: "home-essentials", label: "Home Essentials" },
] as const;

export const getProductsByRoom = getProductsByCategory;
export const ROOMS = CATEGORIES.map(c => ({ slug: c.slug, label: c.label, emoji: "" as string }));

export const products: readonly Product[] = [
  {
    name: "Soap Dispensers",
    price: "$44",
    category: "bathroom",
    asin: "https://amzn.to/3Zc2rUe",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1_iuzsJSeadTAVgvsv7R6B265izIpn8p2',
  },
  {
    name: "Luxury Towel Set",
    price: "$44",
    category: "bathroom",
    asin: "https://amzn.to/4tqhDv1",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1JWL-hwifUu7YP6bO53gRp4b9wkSAHmDi',
  },
  {
    name: "Waffle Bath Rug",
    price: "$20",
    category: "bathroom",
    asin: "https://amzn.to/3Z4Gu9J",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1Q6MDz3PyxrX35raX6u0jfDLj57SMcP_o',
  },
  {
    name: "Travertine Tissue Box",
    price: "$30",
    category: "bathroom",
    asin: "https://amzn.to/46oeEZR",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1pC909hh2e1GgpPe4_dtg2PmdCoZjqg6G',
  },
  {
    name: "Bathroom Sink Accessory Set",
    price: "$37",
    category: "bathroom",
    asin: "https://amzn.to/4a9iJSX",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1SPBpL3WP0sCDZk2pdQtCYIRp4fxWG7jB',
  },
  {
    name: "Toilet Brush",
    price: "$23",
    category: "bathroom",
    asin: "https://amzn.to/3McsuI0",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=108SDB_R7zjQsxl_1-3-FIav6XtLa5NH8',
  },
  {
    name: "Metal Toothbrush Holder",
    price: "$16",
    category: "bathroom",
    asin: "https://amzn.to/46gmWCX",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1bhCIg9FHLlRu8yhANC6rpZxX5q9Q9Xa5',
  },
  {
    name: "Wood Stool",
    price: "$105",
    category: "bathroom",
    asin: "https://amzn.to/3LHbgT1",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1TBQWcSFTTQJItUJa2MgRaqne00wg-wNK',
  },
  {
    name: "Luxury Waffle Robe",
    price: "$90",
    category: "bathroom",
    asin: "https://amzn.to/4t3Lf0Z",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1gUUlXionzRnMYdfxSESlsRBbXUHouWFz',
  },
  {
    name: "Under Sink Organizer",
    price: "$50",
    category: "bathroom",
    asin: "https://amzn.to/3LFnBqQ",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1yq3Mg_o4PBTBG4nqJAeSllcvWQVo5kHZ',
  },
  {
    name: "Woven Trash Bin",
    price: "$47",
    category: "bathroom",
    asin: "https://amzn.to/3ZKBozq",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1GbQez3wu8n6FBLMKk6jmN3iRc3D13boV',
  },
  {
    name: "Brush Holder",
    price: "$36",
    category: "bathroom",
    asin: "https://amzn.to/4t6HwPZ",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1Ch1ZD6QmTB2F0LhixWsOMIKXMVSkO58P',
  },
  {
    name: "Organizational Drawers",
    price: "$36",
    category: "bathroom",
    asin: "https://amzn.to/4t5v3MA",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1tMelo1T9VPyp5aG5Dag1eGFT8EgBXrzr',
  },
  {
    name: "Marble Cutting Board",
    price: "$44",
    category: "kitchen",
    asin: "https://amzn.to/3LYZgMJ",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1QxNuOpa3uCl8TiNBqqwKe_ua5siUxUCv',
  },
  {
    name: "Sponge Holder",
    price: "$27",
    category: "kitchen",
    asin: "https://amzn.to/4tjQj1q",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1nJPO4AY9dee0YLhs1X70QpFrAzKE4C_E',
  },
  {
    name: "Utensil Organizer",
    price: "$47",
    category: "kitchen",
    asin: "https://amzn.to/3Zerq9r",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1yyZ1OobjwCpmg7-2NU52AGo5MIWQ2r3X',
  },
  {
    name: "Calcite Spoon Rest",
    price: "$20",
    category: "kitchen",
    asin: "https://amzn.to/4a3ihpf",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=15dZ92DJX5Mvn9LD363K4Sa16Pt9SMlkG',
  },
  {
    name: "Bag Storage Organizer",
    price: "$23",
    category: "kitchen",
    asin: "https://amzn.to/3O5I4FT",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=13jNQYIu4CtWRBjC2hPdFS6KLRuZUHXov',
  },
  {
    name: "Lazy Susan",
    price: "$16",
    category: "kitchen",
    asin: "https://amzn.to/4r0E3Be",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1oBsKy246cN6z2XanpyVQ2PuUo1FiNVlN',
  },
  {
    name: "Trivets",
    price: "$15",
    category: "kitchen",
    asin: "https://amzn.to/45AIWse",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1rh4V_y8Z-KlBcIdk6j71oMzM3J_Q_V9X',
  },
  {
    name: "Serax Glass Water Pitcher",
    price: "$56",
    category: "kitchen",
    asin: "https://amzn.to/4ey6NOk",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1ro9qBOx5Zj2IAaOLQm4SZUN8RMIH8c6I',
  },
  {
    name: "Stoneware Cheese Board",
    price: "$24.99",
    category: "kitchen",
    asin: "https://amzn.to/4ctj3yl",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1PQIp90YwcQcV0uOjpJqkj_Xpktt12eEV',
  },
  {
    name: "Dish Towels",
    price: "$20",
    category: "kitchen",
    asin: "https://amzn.to/49Uicny",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1GtCNKl-bbhgBF5P-4LU__JYJ1aUlgBjG',
  },
  {
    name: "Footed Fruit Bowl",
    price: "$40",
    category: "kitchen",
    asin: "https://amzn.to/4a2WCxd",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1QMxDfnUPgwV5QFwjiDqPVoVkJiKFE7vw',
  },
  {
    name: "Olive Oil Cruet",
    price: "$46",
    category: "kitchen",
    asin: "https://amzn.to/4bryK8Z",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1MxbYEwnL3CWQ8jty4gp2nibxlGBDb9iT',
  },
  {
    name: "Potholders",
    price: "$98",
    category: "kitchen",
    asin: "https://amzn.to/3Mct48E",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1pp_oH0nCXIxxuXH1lQtCtRgZUqbz0kvS',
  },
  {
    name: "Clean Dirty Sign",
    price: "$37",
    category: "kitchen",
    asin: "https://amzn.to/4bDM8Hn",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=107nkUmc0GRoqR2ISh3Dzcx3pfp7HpjYM',
  },
  {
    name: "Stainless Steel Crock",
    price: "$24",
    category: "kitchen",
    asin: "https://amzn.to/4qjK8HV",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1sPfF5xVa-7e4FeWxHa2T0SSbddy6t51H',
  },
  {
    name: "Soap Dispensers Kitchen",
    price: "$33",
    category: "kitchen",
    asin: "https://amzn.to/49U2fzb",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=154Jar3AF-_f6qsrwtmmviTnHK7BweGjY',
  },
  {
    name: "Salt Cellar",
    price: "$160",
    category: "kitchen",
    asin: "https://amzn.to/4qefPlW",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1OJ0tG0C2wOoIHiC8kZmAp7OytWoWDz88',
  },
  {
    name: "Paper Towel Holder",
    price: "$37",
    category: "kitchen",
    asin: "https://amzn.to/45J1eHG",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=13ZG6tRA4WcSh2ni9R2Zm3Oq4tzpJIQIh',
  },
  {
    name: "Waffle Weave Pillowcases",
    price: "$24",
    category: "bedroom",
    asin: "https://amzn.to/4t5urXi",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1J7OaDuzqnSvGo3gXwRQstsncNnDfe1x8',
  },
  {
    name: "Linen Euro Shams",
    price: "$38",
    category: "bedroom",
    asin: "https://amzn.to/4k8zemR",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1FNiD6DUvQiX6F6m0b8VSd8bzreVOJt85',
  },
  {
    name: "Bedside Lamp",
    price: "$70",
    category: "bedroom",
    asin: "https://amzn.to/49QczIx",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1jqC-aDJLssGNMJG1zy0pXqlM5JE8aL0c',
  },
  {
    name: "Floor Full Length Mirror",
    price: "$117",
    category: "bedroom",
    asin: "https://amzn.to/4kbp2tV",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1Zp2dyXDUjA8PBhLoLrAHNMq0bLmuT9Zq',
  },
  {
    name: "Roller Hamper",
    price: "$38",
    category: "bedroom",
    asin: "https://amzn.to/4q5IXeU",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1hzhtK7hDjvbtYswVIYSo5TYUVy-qK1uT',
  },
  {
    name: "Boucle Lumbar Pillow Case",
    price: "$20",
    category: "bedroom",
    asin: "https://amzn.to/4rnolQy",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1o6Gcmr78Yq_j4QsCvy2Ltl6nt1kU8pr0',
  },
  {
    name: "Silver Tray",
    price: "$63",
    category: "home-essentials",
    asin: "https://amzn.to/4qavsL7",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1OyIcODrl7LwEqq2EBNKOu7eV3RcyXJx4',
  },
  {
    name: "Velvet Bench",
    price: "$180",
    category: "home-essentials",
    asin: "https://amzn.to/3NUXnBa",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=16ey0F7riLbRetaHB9m47AD6f6FGvl_9V',
  },
  {
    name: "Leather Boxes",
    price: "$75",
    category: "home-essentials",
    asin: "https://amzn.to/4rpYw2j",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1gdtNpBWULhP_NrWo3SSpPJ0G957lQPEk',
  },
  {
    name: "Stone Bowl",
    price: "$30",
    category: "home-essentials",
    asin: "https://amzn.to/4rpYEyP",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=14uYPtmTv_8aa-Rish2Lq17YPCwkj2RD-',
  },
  {
    name: "Throw Pillows",
    price: "$20",
    category: "home-essentials",
    asin: "https://amzn.to/4t9oVTz",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=17X2NtAQT0uZKMlYgHAtyvznuJDB9xd9p',
  },
  {
    name: "Stackable Flat Jewelry Tray",
    price: "$40",
    category: "home-essentials",
    asin: "https://amzn.to/4k4CyiK",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1grNQR0YqTDo6-QcbNVApnlfkliRmuFzT',
  },
  {
    name: "Wall Mounted Shelf",
    price: "$36",
    category: "home-essentials",
    asin: "https://amzn.to/45F5jwv",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1SxmTnyIE1cYIZDFEfGkyqgsV4qfrrtA0',
  },
  {
    name: "Woven Storage Boxes",
    price: "$33",
    category: "home-essentials",
    asin: "https://amzn.to/4c1drLJ",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1E_u5_c9NNFryERYXXUTsYklUUJaFObnI',
  },
  {
    name: "Wavy Key Bowl",
    price: "$80",
    category: "home-essentials",
    asin: "https://amzn.to/4c1WWyV",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1ZT1NVP-BvbNCG96HZgdbIyua9DgHHlsS',
  },
  {
    name: "Incense",
    price: "$50",
    category: "home-essentials",
    asin: "https://amzn.to/3Z3OXdf",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1ZjjUR7fubx1Qwd_9rG-SSOTmz2HY2Ceg',
  },
  {
    name: "Woody Ceramic Candle",
    price: "$40",
    category: "home-essentials",
    asin: "https://amzn.to/4re2Y3O",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1qgTIWkAHII8qrWRfAnMEV6R9-ZSbmGka',
  },
  {
    name: "Self Watering Pot",
    price: "$16",
    category: "home-essentials",
    asin: "https://amzn.to/4qLb0kX",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1EN0kYCtx9-K3_tdVBuiDT1BS9ce5YBM6',
  },
  {
    name: "Throw Pillowcase",
    price: "$16",
    category: "home-essentials",
    asin: "https://amzn.to/4qIJhRW",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1HMwG5kuEgEM_45NV2SXmeg6SMpNQKHN_',
  },
  {
    name: "Hooks Set Of 5",
    price: "$30",
    category: "home-essentials",
    asin: "https://amzn.to/4krGeeR",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1rEW5snV0YCh2MVcpvGt1iT4i6QbUwgWG',
  },
  {
    name: "Rattan Wicker Mirror",
    price: "$105",
    category: "home-essentials",
    asin: "https://amzn.to/48PT8OV",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1VkAsOAmIuBRAXsFtlWWgr7OLHtAUfQtl',
  },
  {
    name: "Taper Candle Shell Wall Sconce",
    price: "$71",
    category: "home-essentials",
    asin: "https://amzn.to/4tr1Ifc",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1Z_Nuo5Cpqc7t6SDnRA6q1DoDSgDTQ8Yq',
  },
  {
    name: "Glass Ice Bucket",
    price: "$55",
    category: "home-essentials",
    asin: "https://amzn.to/4tYvszX",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1ZEADQaTaDIVc70WiYu9CrDjmBS37IE8X',
  },
  {
    name: "Resin Decorative Storage Box",
    price: "$64",
    category: "home-essentials",
    asin: "https://amzn.to/3OE3vhS",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=18l_okzZjjdNCKmFNfJgkGSOGyEdbl0-q',
  },
  {
    name: "Clay Velvet Upholstered Chair",
    price: "$1200",
    category: "home-essentials",
    asin: "https://amzn.to/493SEVr",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1HWN-FvBdhwGeGMgxk0SsLPZOKGbKbWvE',
  },
  {
    name: "Resin Striped Photo Frame",
    price: "$17.03",
    category: "home-essentials",
    asin: "https://amzn.to/3OGP3px",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1SWDUY5B3KYl8kwFNMU_mkzPef0NSf90C',
  },
  {
    name: "Hand-Painted Stoneware Bowl",
    price: "$124.99",
    category: "home-essentials",
    asin: "https://amzn.to/4vLQe7G",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1wyKdLCQB3szlK0aK-n1edD37Za8xvjn3',
  },
  {
    name: "Hand-Forged Metal Taper Candle Holder",
    price: "$21.99",
    category: "home-essentials",
    asin: "https://amzn.to/4eDgpqY",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1vpiisEW93mHe4x_8TZ6XujR6MZ2f38T1',
  },
  {
    name: "Footed Catchall",
    price: "$68",
    category: "home-essentials",
    asin: "https://amzn.to/4kaAkhN",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=18IrqMKE6PHIjVdtpuVf2yo6fxFY7KKJz',
  },
  {
    name: "Salt & Stone Scented Candle",
    price: "$49",
    category: "home-essentials",
    asin: "https://amzn.to/3OFo25F",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=164cafY3e9tbaFdF-d7WlXnD1mAlMR5Jv',
  },
  {
    name: "Travertine Wave Bookends",
    price: "$37",
    category: "home-essentials",
    asin: "https://amzn.to/3QGAzqd",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1JW_mYQlpI5ybDUkttDq9srto3PSqOrXH',
  },
  {
    name: "Metal Martini Cocktail Table",
    price: "$65",
    category: "home-essentials",
    asin: "https://amzn.to/42n843l",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1JfXf0JgKzQR-sK9sp6cw2eeeWUcjXlZh',
  },
  {
    name: "Acrylic Book Holder",
    price: "$34",
    category: "home-essentials",
    asin: "https://amzn.to/4vFzYVL",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=11SB75EBEcA7PH_Sl5rdzziYTNkVyv0Tn',
  },
  {
    name: "Wicker Storage Basket With Lid Set Of 3",
    price: "$50",
    category: "home-essentials",
    asin: "https://amzn.to/4e4xqdv",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=11B1AsrzLvX43qubl7OInHuO1fKv3sC8D',
  },
  {
    name: "Disposable Cotton Cocktail Napkins",
    price: "$19",
    category: "home-essentials",
    asin: "https://amzn.to/48MLfK6",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1eyIY2NsU7iUo12hXHEMcVbdEtUPm-oH9',
  },
  {
    name: "Marbled Resin Cheese Board",
    price: "$62",
    category: "home-essentials",
    asin: "https://amzn.to/4sM40V5",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1ZEADQaTaDIVc70WiYu9CrDjmBS37IE8X',
  },
  {
    name: "Night Light",
    price: "$26",
    category: "home-essentials",
    asin: "https://amzn.to/4a90dKx",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1NioQrtii1YBa-nreHylqivxkYjZvosFq',
  },
  {
    name: "Wood Tissue Cover",
    price: "$20",
    category: "home-essentials",
    asin: "https://amzn.to/45G9tEq",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=19KlScup_uOVWWPBqXA_YVc_j9EwNxmtR',
  },
  {
    name: "Wall Hook Set",
    price: "$30",
    category: "home-essentials",
    asin: "https://amzn.to/4krGeeR",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1i8kDeLCf1Km7VK4p57SCoFptiGB9Ejqw',
  },
  {
    name: "Cast Iron Candelabra",
    price: "$98",
    category: "home-essentials",
    asin: "https://amzn.to/45GSzWf",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=12UsP97RmNFOUvM8n7SNGXnRoOhD-ZFUe',
  },
  {
    name: "Fig Leaf & Lemon Ceramic Candle",
    price: "$40",
    category: "home-essentials",
    asin: "https://amzn.to/45AIeey",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1K-Be7lW_l1tQH67wfBlgEKlH-0I2-rAn',
  },
  {
    name: "Incense Cone Diffuser",
    price: "$27",
    category: "home-essentials",
    asin: "https://amzn.to/4blTr6i",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1RTvdFzk3uU0LSid2iM-xr5E3y2Bm2C_C',
  },
  {
    name: "Organizational Box",
    price: "$34",
    category: "home-essentials",
    asin: "https://amzn.to/4t9z2HV",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1gQfAqdfAH9JHGfj4NSqX_wuhoXeAHg6N',
  },
  {
    name: "Side Table",
    price: "$272",
    category: "home-essentials",
    asin: "https://amzn.to/4t92XQw",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=18tYb1BcYxIpUGa7HRwFVV4F6X7dS4P57',
  },
  {
    name: "6 Ft Artificial Sumac Tree",
    price: "$126",
    category: "home-essentials",
    asin: "https://amzn.to/3NFfNGb",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1hw_6Z0umdtARhrypQhIzewr8DZga4TR7',
  },
  {
    name: "Concrete Coffee Table",
    price: "$407",
    category: "home-essentials",
    asin: "https://amzn.to/4kgOM8c",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1_5ple1bM3Ia6tGLmvDgIc4WdW1VnFg0m',
  },
  {
    name: "Oud Agarwood Ceramic Candle",
    price: "$40",
    category: "home-essentials",
    asin: "https://amzn.to/45AIeey",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1K-Be7lW_l1tQH67wfBlgEKlH-0I2-rAn',
  },
  {
    name: "Tortoises Vase",
    price: "$34",
    category: "home-essentials",
    asin: "https://amzn.to/4t7jFQj",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1hFp3Taa9rsCWkjEPAA6NAVe4vyjBBrOp',
  },
  {
    name: "Stone Bookends",
    price: "$36",
    category: "home-essentials",
    asin: "https://amzn.to/4q6uWOc",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=18qlzb-l1z5V0NelRgutab5ZTTAmDPZ_y',
  },
  {
    name: "Leather Throw Pillow",
    price: "$60",
    category: "home-essentials",
    asin: "https://amzn.to/4qP6odP",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1iyD7tMrSmRJKm9QSxD42rghvmqeWFPQQ',
  },
  {
    name: "Calacatta Dish",
    price: "$54",
    category: "home-essentials",
    asin: "https://amzn.to/4tzaB6y",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1d-58eK7DsnertSDyRWOHv83lPY8Hk5hi',
  },
  {
    name: "Table Lamp",
    price: "$187",
    category: "home-essentials",
    asin: "https://amzn.to/4k5R5uJ",
    featured: true,
    image: 'https://drive.google.com/uc?export=view&id=1wq0-fwu8PEt2vCVXSwmr90Sdp3T1fdYY',
  },
  {
    name: "Magnetic Cord Holder",
    price: "$20",
    category: "home-essentials",
    asin: "https://amzn.to/4q3dSIL",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1URpVbecnjjn_XgheoiriZticDFqG8sr6',
  },
  {
    name: "Resin Hooks Set",
    price: "$23",
    category: "home-essentials",
    asin: "https://amzn.to/4bryneB",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1T7gprQ1TY0zpRY0p0hGTU2lYr8SjjGZ4',
  },
  {
    name: "Basket Storage",
    price: "$32",
    category: "home-essentials",
    asin: "https://amzn.to/4qMT21o",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1S_qqRE9Ddb1s4dyDUKJOQzxEoWyYhy48',
  },
  {
    name: "Wood Catchall Box",
    price: "$24",
    category: "home-essentials",
    asin: "https://amzn.to/4q19zO5",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1GfLQgLq0qdGlXpoKrtP_omQh5VAActmm',
  },
  {
    name: "Basket Set Of 4",
    price: "$44",
    category: "home-essentials",
    asin: "https://amzn.to/4bVOfpW",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=14fHl6nndxTZlzpkzzn64sZA1wKrd7vMA',
  },
  {
    name: "Under Sink Storage",
    price: "$37",
    category: "home-essentials",
    asin: "https://amzn.to/4kbcdzC",
    featured: false,
    image: 'https://drive.google.com/uc?export=view&id=1yq3Mg_o4PBTBG4nqJAeSllcvWQVo5kHZ',
  },
] as const;